import { Trade } from './types';

const now = Math.floor(Date.now() / 1000);
const HOUR = 3600;
const MIN = 60;

export const MOCK_TRADES: Trade[] = [
  // === DAY 1: Getting Started (48-36h ago) — Random guesses ===
  {
    transaction_id: 'TXN001',
    contract_id: 98001,
    purchase_time: now - 48 * HOUR,
    sell_time: now - 48 * HOUR + 1 * MIN,
    buy_price: 5.0,
    sell_price: 0,
    profit: -5.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '1m',
    payout: 9.5,
    market_context: {
      trend: 'bearish',
      volatility: 'medium',
      description:
        'Price had been declining for 20 minutes. Clear downtrend on 1-min chart.',
    },
  },
  {
    transaction_id: 'TXN002',
    contract_id: 98002,
    purchase_time: now - 47 * HOUR,
    sell_time: now - 47 * HOUR + 1 * MIN,
    buy_price: 5.0,
    sell_price: 9.5,
    profit: 4.5,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'PUT',
    duration: '1m',
    payout: 9.5,
    market_context: {
      trend: 'bearish',
      volatility: 'medium',
      description: 'Continuation of the downtrend. Price falling steadily.',
    },
  },
  {
    transaction_id: 'TXN003',
    contract_id: 98003,
    purchase_time: now - 46 * HOUR,
    sell_time: now - 46 * HOUR + 2 * MIN,
    buy_price: 5.0,
    sell_price: 0,
    profit: -5.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '2m',
    payout: 9.8,
    market_context: {
      trend: 'bearish',
      volatility: 'high',
      description:
        'Volatile downward movement. Sharp price drops with brief recoveries.',
    },
  },
  {
    transaction_id: 'TXN004',
    contract_id: 98004,
    purchase_time: now - 45 * HOUR,
    sell_time: now - 45 * HOUR + 5 * MIN,
    buy_price: 10.0,
    sell_price: 0,
    profit: -10.0,
    underlying_symbol: 'R_50',
    underlying_name: 'Volatility 50 Index',
    contract_type: 'CALL',
    duration: '5m',
    payout: 19.0,
    market_context: {
      trend: 'sideways',
      volatility: 'low',
      description: 'R_50 moving in tight range. No clear direction.',
    },
  },
  {
    transaction_id: 'TXN005',
    contract_id: 98005,
    purchase_time: now - 44 * HOUR,
    sell_time: now - 44 * HOUR + 1 * MIN,
    buy_price: 5.0,
    sell_price: 9.5,
    profit: 4.5,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'PUT',
    duration: '1m',
    payout: 9.5,
    market_context: {
      trend: 'bearish',
      volatility: 'medium',
      description: 'Resumed downtrend after brief consolidation.',
    },
  },

  // === DAY 1 EVENING: Frustration kicks in (36-24h ago) — Emotional trading ===
  {
    transaction_id: 'TXN006',
    contract_id: 98006,
    purchase_time: now - 36 * HOUR,
    sell_time: now - 36 * HOUR + 1 * MIN,
    buy_price: 10.0,
    sell_price: 0,
    profit: -10.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '1m',
    payout: 19.0,
    market_context: {
      trend: 'bearish',
      volatility: 'high',
      description: 'Sharp sell-off in progress. Price dropping rapidly.',
    },
  },
  {
    transaction_id: 'TXN007',
    contract_id: 98007,
    purchase_time: now - Math.floor(35.5 * HOUR),
    sell_time: now - Math.floor(35.5 * HOUR) + 1 * MIN,
    buy_price: 20.0,
    sell_price: 0,
    profit: -20.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '1m',
    payout: 38.0,
    market_context: {
      trend: 'bearish',
      volatility: 'high',
      description:
        'Sell-off continuing. No signs of reversal. Trader doubled stake after previous loss.',
    },
  },
  {
    transaction_id: 'TXN008',
    contract_id: 98008,
    purchase_time: now - 34 * HOUR,
    sell_time: now - 34 * HOUR + 2 * MIN,
    buy_price: 5.0,
    sell_price: 9.8,
    profit: 4.8,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'PUT',
    duration: '2m',
    payout: 9.8,
    market_context: {
      trend: 'bearish',
      volatility: 'medium',
      description:
        'Downtrend stabilizing. Steady decline with lower volatility.',
    },
  },
  {
    transaction_id: 'TXN009',
    contract_id: 98009,
    purchase_time: now - 33 * HOUR,
    sell_time: now - 33 * HOUR + 5 * MIN,
    buy_price: 15.0,
    sell_price: 0,
    profit: -15.0,
    underlying_symbol: '1HZ100V',
    underlying_name: 'Volatility 100 (1s) Index',
    contract_type: 'CALL',
    duration: '5m',
    payout: 28.5,
    market_context: {
      trend: 'sideways',
      volatility: 'high',
      description:
        '1-second index with extreme tick-by-tick volatility. No clear trend.',
    },
  },
  {
    transaction_id: 'TXN010',
    contract_id: 98010,
    purchase_time: now - 32 * HOUR,
    sell_time: now - 32 * HOUR + 1 * MIN,
    buy_price: 5.0,
    sell_price: 0,
    profit: -5.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'PUT',
    duration: '1m',
    payout: 9.5,
    market_context: {
      trend: 'bullish',
      volatility: 'high',
      description:
        'Sudden reversal. Market spiked upward after simulated news event.',
    },
  },

  // === DAY 2: Some improvement (24-12h ago) — Pattern recognition emerging ===
  {
    transaction_id: 'TXN011',
    contract_id: 98011,
    purchase_time: now - 24 * HOUR,
    sell_time: now - 24 * HOUR + 2 * MIN,
    buy_price: 5.0,
    sell_price: 9.8,
    profit: 4.8,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '2m',
    payout: 9.8,
    market_context: {
      trend: 'bullish',
      volatility: 'low',
      description: 'Clean uptrend forming. Consistent higher highs.',
    },
  },
  {
    transaction_id: 'TXN012',
    contract_id: 98012,
    purchase_time: now - 23 * HOUR,
    sell_time: now - 23 * HOUR + 2 * MIN,
    buy_price: 5.0,
    sell_price: 9.8,
    profit: 4.8,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '2m',
    payout: 9.8,
    market_context: {
      trend: 'bullish',
      volatility: 'low',
      description: 'Uptrend continues. Smooth price action.',
    },
  },
  {
    transaction_id: 'TXN013',
    contract_id: 98013,
    purchase_time: now - 22 * HOUR,
    sell_time: now - 22 * HOUR + 5 * MIN,
    buy_price: 10.0,
    sell_price: 0,
    profit: -10.0,
    underlying_symbol: 'R_75',
    underlying_name: 'Volatility 75 Index',
    contract_type: 'PUT',
    duration: '5m',
    payout: 19.0,
    market_context: {
      trend: 'bullish',
      volatility: 'medium',
      description: 'R_75 in steady uptrend. Buying pressure dominant.',
    },
  },
  {
    transaction_id: 'TXN014',
    contract_id: 98014,
    purchase_time: now - 20 * HOUR,
    sell_time: now - 20 * HOUR + 1 * MIN,
    buy_price: 5.0,
    sell_price: 9.5,
    profit: 4.5,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '1m',
    payout: 9.5,
    market_context: {
      trend: 'bullish',
      volatility: 'low',
      description: 'Continuation of bullish trend on R_100.',
    },
  },
  {
    transaction_id: 'TXN015',
    contract_id: 98015,
    purchase_time: now - 18 * HOUR,
    sell_time: now - 18 * HOUR + 5 * MIN,
    buy_price: 25.0,
    sell_price: 0,
    profit: -25.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '5m',
    payout: 47.5,
    market_context: {
      trend: 'sideways',
      volatility: 'high',
      description:
        'Market entered choppy range after trend ended. High volatility in both directions.',
    },
  },

  // === DAY 3: Today (12-0h ago) — Mixed results, still learning ===
  {
    transaction_id: 'TXN016',
    contract_id: 98016,
    purchase_time: now - 12 * HOUR,
    sell_time: now - 12 * HOUR + 1 * MIN,
    buy_price: 5.0,
    sell_price: 0,
    profit: -5.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'PUT',
    duration: '1m',
    payout: 9.5,
    market_context: {
      trend: 'bullish',
      volatility: 'medium',
      description: 'New bullish trend emerging. Higher lows forming.',
    },
  },
  {
    transaction_id: 'TXN017',
    contract_id: 98017,
    purchase_time: now - 10 * HOUR,
    sell_time: now - 10 * HOUR + 2 * MIN,
    buy_price: 5.0,
    sell_price: 9.8,
    profit: 4.8,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '2m',
    payout: 9.8,
    market_context: {
      trend: 'bullish',
      volatility: 'low',
      description: 'Clean bullish movement. Good momentum.',
    },
  },
  {
    transaction_id: 'TXN018',
    contract_id: 98018,
    purchase_time: now - 8 * HOUR,
    sell_time: now - 8 * HOUR + 5 * MIN,
    buy_price: 10.0,
    sell_price: 0,
    profit: -10.0,
    underlying_symbol: 'R_50',
    underlying_name: 'Volatility 50 Index',
    contract_type: 'PUT',
    duration: '5m',
    payout: 19.0,
    market_context: {
      trend: 'sideways',
      volatility: 'high',
      description: 'R_50 in ranging market with unpredictable volatility spikes.',
    },
  },
  {
    transaction_id: 'TXN019',
    contract_id: 98019,
    purchase_time: now - 5 * HOUR,
    sell_time: now - 5 * HOUR + 2 * MIN,
    buy_price: 5.0,
    sell_price: 9.8,
    profit: 4.8,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'CALL',
    duration: '2m',
    payout: 9.8,
    market_context: {
      trend: 'bullish',
      volatility: 'low',
      description: 'Steady uptrend. Low volatility, easy to read.',
    },
  },
  {
    transaction_id: 'TXN020',
    contract_id: 98020,
    purchase_time: now - 2 * HOUR,
    sell_time: now - 2 * HOUR + 5 * MIN,
    buy_price: 10.0,
    sell_price: 0,
    profit: -10.0,
    underlying_symbol: 'R_100',
    underlying_name: 'Volatility 100 Index',
    contract_type: 'PUT',
    duration: '5m',
    payout: 19.0,
    market_context: {
      trend: 'bullish',
      volatility: 'medium',
      description: 'Uptrend intact but trader bet against it.',
    },
  },
];
